-- Drop existing tables
DROP TABLE IF EXISTS tournament_teams CASCADE;
DROP TABLE IF EXISTS league_teams CASCADE;
DROP TABLE IF EXISTS leagues CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS tournaments CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS staff_members CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;

-- Drop existing types
DROP TYPE IF EXISTS riot_region CASCADE;
DROP TYPE IF EXISTS tournament_status CASCADE;
DROP TYPE IF EXISTS player_role CASCADE;
DROP TYPE IF EXISTS player_rank CASCADE;
DROP TYPE IF EXISTS staff_role CASCADE;
DROP TYPE IF EXISTS region CASCADE;

-- Drop existing functions
DROP FUNCTION IF EXISTS is_owner CASCADE;
DROP FUNCTION IF EXISTS is_platform_admin CASCADE;
DROP FUNCTION IF EXISTS can_manage_team CASCADE;
DROP FUNCTION IF EXISTS is_org_admin CASCADE;
DROP FUNCTION IF EXISTS is_tournament_registration_open CASCADE;
DROP FUNCTION IF EXISTS update_tournament_team_count CASCADE;
